# Site settings
title: Dorothy Signo
email: dorothysigno@gmail.com
url: https://d-signo.github.io/cyber-portfolio
description: "Portfolio of cybersecurity work samples for a junior-level cyber security professional."
keywords: "cybersecurity, cyber, security, portfolio, tech"
skills: "Cybersecurity - Analyst - Ethical Hacker"
meta_author: Signo Dorothy

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: A6E1FA #80B3FF
  primary-rgb: "166,255,250" #"128,179,255"
  secondary: 0A2472 #FD6E8A
  secondary-dark: 00072D #A2122F

# Footer settings
footer:
  copyright: Dorothy Signo
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/dorothy-signo-88623510b/
  - title: github
    url: https://github.com/d-signo/

# Email Address (make sure to include "mailto:" before your email!)
email:
  email-url: mailto:dorothysigno@gmail.com

# Postal address (add as many lines as necessary)
location:
  - line: Seattle, Washington

# Credits content

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
